stages:
  - build
  - test
<<<<<<< HEAD
<<<<<<< HEAD
<<<<<<< HEAD
<<<<<<< HEAD
  - publish
  - deploy
<<<<<<< HEAD
=======
>>>>>>> 1a0a1ad (Added prod mongo config)
=======
  - publish
  - deploy

>>>>>>> 2d9a3fe (Updated CI/CD pipeline)


# BUILD_PHASE
#================
build_phase:
  variables:
    SPRING_PROFILES_ACTIVE: "prod"
  stage: build
  script: ./gradlew --build-cache assemble --info
  image: gradle:7.2.0-jdk11
  cache:
    key: "$CI_COMMIT_REF_NAME"
    policy: push
    paths:
      - build
      - .gradle
  only:
    - main

# TEST_PHASE
#=============
test_phase:
  variables:
    SPRING_PROFILES_ACTIVE: "prod"
  stage: test
  script: ./gradlew test check --info
  image: gradle:7.2.0-jdk11
  cache:
    key: "$CI_COMMIT_REF_NAME"
    policy: pull
    paths:
      - build
      - .gradle
  only:
    - main
<<<<<<< HEAD
<<<<<<< HEAD


# PUBLISH_PHASE
#==================
publish_phase:
  stage:  publish
  before_script:
    - echo $DOCKER_REPO_PASSWORD | docker login --username $DOCKER_REPO_USERNAME --password-stdin
  image:  docker:git
  services:
    - docker:dind
  script:
    - docker build -t $DOCKER_REPO_USERNAME/$DOCKER_REPO_NAME:doc --build-arg password=$PASSWORD .
    - docker push $DOCKER_REPO_USERNAME/$DOCKER_REPO_NAME:doc
=======

# PUBLISH_PHASE
#================
publish_phase:
  stage:  publish
  before_script:
    - echo $DOCKER_REPO_PASSWORD | docker login --username $DOCKER_REPO_USERNAME --password-stdin
  image:  docker:git
  services:
    - docker:dind
  script:
    - docker build --platform linux/amd64 -t sital12/markdowner:auth .
    - docker push $DOCKER_REPO_USERNAME/$DOCKER_REPO_NAME:auth
>>>>>>> def422d (added Dockerfile and fixed CI/CD pipeline)
  cache:
    policy: pull
    key:  "$CI_COMMIT_REF_NAME"
    paths:
      - build
<<<<<<< HEAD
<<<<<<< HEAD

# DEPLOY PHASE
##===============
=======

# Deploy Phase
#==============
>>>>>>> 70a0dc6 (Updated properties and encoded urls)
deploy_assets:
  stage: deploy
  image: google/cloud-sdk:latest
  script:
    - echo $GCP_CREDENTIALS > /tmp/gcp_credentials.json
    - gcloud auth activate-service-account --key-file /tmp/gcp_credentials.json
    - gcloud config set project markdowner
<<<<<<< HEAD
    - gcloud container clusters get-credentials  markdowner-cluster --region us-central1-a --project markdowner
    - kubectl patch deployment doc-app-deployment -p "{\"spec\":{\"template\":{\"metadata\":{\"labels\":{\"date\":\"`date +'%s'`\"}}}}}"
  only:
    - main
=======
>>>>>>> 1a0a1ad (Added prod mongo config)
=======
>>>>>>> def422d (added Dockerfile and fixed CI/CD pipeline)
=======
    - gcloud container clusters get-credentials markdowner-cluster --region us-central1-a --project markdowner
    - kubectl patch deployment auth-app-deployment -p "{\"spec\":{\"template\":{\"metadata\":{\"labels\":{\"date\":\"`date +'%s'`\"}}}}}"
  only:
    - main

>>>>>>> 70a0dc6 (Updated properties and encoded urls)
=======
=======
  - publish
>>>>>>> 1410848 (added Dockerfile and fixed CI/CD pipeline)
=======
>>>>>>> af0609b (added deploy stage)

# Angular CLI image



# Build Phase
# What commands are executed in container
#==============

build_phase:
  stage: build
  image: trion/ng-cli
  before_script:
    - npm ci
  script:
    - ng build --prod --output-hashing=all
  cache:
    key: "$CI_COMMIT_REF_NAME"
    policy: push
    paths:
      - dist
      - node_modules

# Test Phase
# =========

test_phase:
  stage: test
  image: trion/ng-cli-karma:9.0.1
  script:
    - ng test --progress false --watch false
  cache:
    policy: pull
    key: "$CI_COMMIT_REF_NAME"
    paths:
      - dist
      - node_modules
<<<<<<< HEAD
>>>>>>> f1a1b22 (Added ficed CI pipeline file with .yml extension)
=======


# Publish  Phase
# ===========

publish_phase:
  stage:  publish
  before_script:
    - echo $DOCKER_REPO_PASSWORD | docker login --username $DOCKER_REPO_USERNAME --password-stdin
  image:  docker:git
  services:
    - docker:dind
  script:
    - docker build -t $DOCKER_REPO_USERNAME/$DOCKER_REPO_NAME:frontend .
    - docker push $DOCKER_REPO_USERNAME/$DOCKER_REPO_NAME:frontend
  cache:
    policy: pull
    key:  "$CI_COMMIT_REF_NAME"
    paths:
      - dist
<<<<<<< HEAD
  
>>>>>>> 00bf48d (fixed pipeline)
=======

# Deploy Phase
#==============+
deploy_assets:
    stage: deploy
    image: google/cloud-sdk:latest
    script:
      - echo $GCP_CREDENTIALS > /tmp/gcp_credentials.json
      - gcloud auth activate-service-account --key-file /tmp/gcp_credentials.json
      - gcloud config set project markdowner
      - gcloud container clusters get-credentials drmarkdown-cluster --region us-central1-a --project markdowner
      - kubectl patch deployment frontend-app-deployment -p "{\"spec\":{\"template\":{\"metadata\":{\"labels\":{\"date\":\"`date +'%s'`\"}}}}}"
    only:
      - main
>>>>>>> af0609b (added deploy stage)
