server:
  port: 9998


jasypt:
  encryptor:
    algorithm: PBEWithMD5AndDES
    iv-generator-classname: org.jasypt.iv.NoIvGenerator
    password: {bcrypt}$2a$10$jt1jtjqS7g.FKpokupSzu.uHYTNtqTszFP6JHC/q9foNa.V2pu74K


# database

spring:
  data:
    mongodb:
      uri: ENC(+rwKqqZAVNi1GBG/mmWIzwpBokNKa0FBTjAxiKhogF0gUgs5AMPaeac8/F+VIYHMKaKSdtZAz7SE2geEmF8NwZzhKGgqftgUrg+VNjbQtyWobt0/f5508cyzpz9rEegqOOdMD54HguAWSuEcwHZ7Vw==)
      database: doc-prod