<<<<<<< HEAD
<<<<<<< HEAD
server:
  port: 9998

=======
>>>>>>> 70a0dc6 (Updated properties and encoded urls)
jasypt:
  encryptor:
    algorithm: PBEWithMD5AndDES
    iv-generator-classname: org.jasypt.iv.NoIvGenerator
<<<<<<< HEAD
    password: ${password}
=======
=======

>>>>>>> 70a0dc6 (Updated properties and encoded urls)

server:
  port: 9999
>>>>>>> 83af4d6 (Created models and database config)

spring:
  data:
    mongodb:
<<<<<<< HEAD
<<<<<<< HEAD
      uri: mongodb://localhost:27017
      database: ENC(qw4udVtkdO6ULBr7B43/mcdV6Hz9pri4)


management:
  endpoints:
    web:
      exposure:
        include: '*'
=======
      host: mongodb://localhost:27017
=======
      uri: mongodb://localhost:27017
>>>>>>> 1a0a1ad (Added prod mongo config)
      database: auth-demo
<<<<<<< HEAD
>>>>>>> 83af4d6 (Created models and database config)
=======

jwt:
  secret:
    key: ENC(2XDppU9hUY8iskc89d1GFBfVfVVo2QWXOAi+IKGXfb2F/Ty9nC+eG5dvztpcF/j9yZehJsiFqUDKs/lmVWuqwpU1oBB9KJifBJjAs0eMm8m68BeaoZOyIGyCkyfMF8nzcsbCAJhxlTs=)

<<<<<<< HEAD
>>>>>>> 5811a10 (created controller, service and daos)
=======
management:
  endpoints:
    web:
      exposure:
        include: '*'
>>>>>>> 84f1262 (Added actuator)
