<<<<<<< HEAD
<<<<<<< HEAD
<<<<<<< HEAD
<<<<<<< HEAD
server:
  port: 9998

# database

=======
>>>>>>> b0abafb (Updated properties and encoded urls)
jasypt:
  encryptor:
    algorithm: PBEWithMD5AndDES
    iv-generator-classname: org.jasypt.iv.NoIvGenerator
    password: ${password}

<<<<<<< HEAD

# database

spring:
  data:
    mongodb:
      uri: ENC(+rwKqqZAVNi1GBG/mmWIzwpBokNKa0FBTjAxiKhogF0gUgs5AMPaeac8/F+VIYHMKaKSdtZAz7SE2geEmF8NwZzhKGgqftgUrg+VNjbQtyWobt0/f5508cyzpz9rEegqOOdMD54HguAWSuEcwHZ7Vw==)
      database: doc-prod
=======
=======
server:
  port: 9999
>>>>>>> 84f1262 (Added actuator)
=======
>>>>>>> 9456ed1 (Updated properties)
=======
>>>>>>> b0abafb (Updated properties and encoded urls)

#Database
spring:
  data:
    mongodb:

      uri: ENC(dWK+dyOU29XcrM2QXapzXMKcp6WeBdRPlT8PmIL0kkHqj3G4FccDujIE1YMqAPhUMc1kMaOGcqMtyDxubPWJ019d2npAcndEsJjTC3+mqWgkR+94/ASCXICGWtUJPkrvqDrup3i89W1dwosKvKLpSg==)
      database: auth-prod

#JWT
jwt:
  secret:
    key: ENC(Dga5lOYuNtN/RCOTlZqkzyqQ26L/d4y/hoGp6OLOCqDIjdreMfsAev+rztyhdGnyDQTY+PRpp2QuDzFqipBlXModmErhQjxP7h10R4WFmeiBayrGNNnPA7bbRFcZLk8sdKnrVS9zFTI=)



>>>>>>> 1a0a1ad (Added prod mongo config)
