<<<<<<< HEAD
server:
  port: 9998

jasypt:
  encryptor:
    algorithm: PBEWithMD5AndDES
    iv-generator-classname: org.jasypt.iv.NoIvGenerator
    password: ${password}
=======

server:
  port: 9999
>>>>>>> 83af4d6 (Created models and database config)

spring:
  data:
    mongodb:
<<<<<<< HEAD
      uri: mongodb://localhost:27017
      database: ENC(qw4udVtkdO6ULBr7B43/mcdV6Hz9pri4)


management:
  endpoints:
    web:
      exposure:
        include: '*'
=======
      host: mongodb://localhost:27017
      database: auth-demo
>>>>>>> 83af4d6 (Created models and database config)
