<<<<<<< HEAD
<<<<<<< HEAD
server:
  port: 9998


jasypt:
  encryptor:
    algorithm: PBEWithMD5AndDES
    iv-generator-classname: org.jasypt.iv.NoIvGenerator
    password: ${password}


# database

spring:
  data:
    mongodb:
      uri: ENC(+rwKqqZAVNi1GBG/mmWIzwpBokNKa0FBTjAxiKhogF0gUgs5AMPaeac8/F+VIYHMKaKSdtZAz7SE2geEmF8NwZzhKGgqftgUrg+VNjbQtyWobt0/f5508cyzpz9rEegqOOdMD54HguAWSuEcwHZ7Vw==)
      database: doc-prod
=======
=======
server:
  port: 9999
>>>>>>> 84f1262 (Added actuator)

spring:
  data:
    mongodb:
      uri: mongodb+srv://sitouls:Uranium12%40@markdowner.1tvtg.mongodb.net/test?retryWrites=true&w=majority
      database: auth-prod

jwt:
  secret:
    key: RWHxVfglggk2ZHBIJSl/RoJmkW3olz/rkBce6oEne38/JCzqRqLO5fD1TUFSxP4Ar4/EzCEtuM4SD4Okccco4C==




>>>>>>> 1a0a1ad (Added prod mongo config)
