<<<<<<< HEAD
server:
  port: 9998

jasypt:
  encryptor:
    algorithm: PBEWithMD5AndDES
    iv-generator-classname: org.jasypt.iv.NoIvGenerator
    password: ${password}
=======

server:
  port: 9999
>>>>>>> 83af4d6 (Created models and database config)

spring:
  data:
    mongodb:
<<<<<<< HEAD
      uri: mongodb://localhost:27017
      database: ENC(qw4udVtkdO6ULBr7B43/mcdV6Hz9pri4)


management:
  endpoints:
    web:
      exposure:
        include: '*'
=======
      host: mongodb://localhost:27017
      database: auth-demo
<<<<<<< HEAD
>>>>>>> 83af4d6 (Created models and database config)
=======

jwt:
  secret:
    key: pFtzHkzwMZWguXpY9XfN0ikS0w7BVgDs7azZaRA+R3b4QWqIBdvkVNzoGSG5dJU/FJ3dIhttfunvh7IY3RhP/Q==

>>>>>>> 5811a10 (created controller, service and daos)
