server:
  port: 9998
jasypt:
  encryptor:
    algorithm: PBEWithMD5AndDES
    iv-generator-classname: org.jasypt.iv.NoIvGenerator


spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017
      database: doc-demo



management:
  endpoints:
    web:
      exposure:
        include: '*'
